import { access, mkdir, writeFile } from 'node:fs/promises';
import sharp from 'sharp';
import { format } from 'prettier';

const names = [
  'eldegirlboss',
  'sleepy-espeon',
  'muscle-milcery',
  'skitty-hi',
  'toggers',
  'calyrex-gamer',
] as const;
const assets: Partial<Record<(typeof names)[number], string>> = {};
await mkdir('public/illustrations', { recursive: true });
for (const name of names) {
  let source = `public/illustrations/${name}.png`;
  try {
    await access(source);
  } catch {
    if (name !== 'calyrex-gamer') continue;
    source = 'public/illustrations/gamerrex.gif';
    try {
      await access(source);
    } catch {
      continue;
    }
  }
  // Fit the transparent original inside a retina-sized canvas; never crop the artwork.
  await sharp(source, { animated: false })
    .rotate()
    .resize(160, 160, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .webp({ quality: 90, alphaQuality: 100 })
    .toFile(`public/illustrations/${name}.webp`);
  assets[name] = `illustrations/${name}.webp`;
}
const source = `// Generated by scripts/illustrations.ts from Grace's original artwork.\nexport const illustrations: Partial<Record<${names.map((name) => JSON.stringify(name)).join(' | ')}, string>> = ${JSON.stringify(assets, null, 2)};\n`;
await writeFile(
  'src/illustrations.ts',
  await format(source, {
    parser: 'typescript',
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
  }),
);
console.log(
  `Prepared ${Object.keys(assets).length} of ${names.length} original illustrations; missing artwork is omitted.`,
);
