// Generated by scripts/illustrations.ts from Grace's original artwork.
export const illustrations: Partial<
  Record<
    'eldegirlboss' | 'sleepy-espeon' | 'muscle-milcery' | 'skitty-hi' | 'toggers' | 'calyrex-gamer',
    string
  >
> = {
  eldegirlboss: 'illustrations/eldegirlboss.webp',
  'sleepy-espeon': 'illustrations/sleepy-espeon.webp',
  'muscle-milcery': 'illustrations/muscle-milcery.webp',
  'skitty-hi': 'illustrations/skitty-hi.webp',
  toggers: 'illustrations/toggers.webp',
  'calyrex-gamer': 'illustrations/calyrex-gamer.webp',
};
